import{S as b,i as L}from"./assets/vendor-46aac873.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const s={form:document.querySelector(".form"),input:document.querySelector(".input"),gallery:document.querySelector(".gallery"),button:document.querySelector(".button"),loader:document.querySelector(".loader")},v="https://pixabay.com/api/",q="41991385-9b19b8bb3d6f1491499417d17";function u({query:o,page:a=1,per_page:n}){const t=`${v}?key=${q}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;return axios.get(t,{params:{page:a,per_page:n}}).then(({data:e})=>e)}function d(o){return o.map(({webformatURL:a,largeImageURL:n,tags:t,likes:e,views:r,comments:c,downloads:p})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img
              class="gallery-image"
              src="${a}"
              alt="${t}"
            />
            <ul class="gallery-info">
              <li class="gallery-info-item">Likes: <span class="descr-span">${e}</span></li>
              <li class="gallery-info-item">Views: <span class="descr-span">${r}</span></li>
              <li class="gallery-info-item">Comments: <span class="descr-span">${c}</span></li>
              <li class="gallery-info-item">Downloads: <span class="descr-span">${p}</span></li>
            </ul> 
          </a>
        </li>`).join("")}function f(){window.scrollBy({top:2*document.querySelector(".gallery-item").getBoundingClientRect().height,behavior:"smooth"})}const m=new b(".gallery-item a",{captionsData:"alt",captionDelay:250}),i={query:"",page:1,maxPage:0,per_page:15};s.form.addEventListener("submit",w);async function w(o){o.preventDefault(),s.gallery.innerHTML="",i.page=1;const a=o.currentTarget;if(i.query=a.elements.query.value.trim(),h(),!i.query){n("The search field can't be empty! Please, enter your request!");return}function n(t){L.show({class:"error-svg",position:"topRight",icon:"error-svg",message:t,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}try{const{hits:t,totalHits:e}=await u(i);i.maxPage=Math.ceil(e/i.per_page),s.gallery.insertAdjacentHTML("beforeend",d(t)),m.refresh(),l(),t.length===0?(n("Sorry, there are no images matching your search query. Please, try again!"),l()):t.length>0&&t.length!==e?(S(),s.button.addEventListener("click",y),l()):(g(),n("We are sorry, but you've reached the end of search results"))}catch{n("Sorry, there is a problem with connection with the server")}finally{l(),a.reset(),f()}}async function y(){i.page+=1,h(),s.button.disabled=!0;try{const{hits:o}=await u(i);s.gallery.insertAdjacentHTML("beforeend",d(o)),m.refresh()}catch{createMessage("Sorry, there is a problem with connection with the server")}finally{l(),s.button.disabled=!1,i.page===i.maxPage&&(l(),g(),s.button.removeEventListener("click",y),createMessage("We are sorry, but you've reached the end of search results")),f()}}function l(){setTimeout(()=>{s.loader.classList.add("is-hidden")},500)}function h(){s.loader.classList.remove("is-hidden")}function g(){s.button.classList.add("is-hidden")}function S(){s.button.classList.remove("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
