import{S as g,i as p}from"./assets/vendor-46aac873.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const o={form:document.querySelector(".form"),input:document.querySelector(".input"),gallery:document.querySelector(".gallery"),searchBtn:document.querySelector(".btn"),button:document.querySelector(".button"),loadMoreBtn:document.querySelector('[data-action="load-more"]'),loader:document.querySelector(".loader")},L="https://pixabay.com/api/",b="41991385-9b19b8bb3d6f1491499417d17";function u({query:n,page:s=1,per_page:a}){const t=`${L}?key=${b}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return axios.get(t,{params:{page:s,per_page:a}}).then(({data:e})=>e)}function f(n){return n.map(({webformatURL:s,largeImageURL:a,tags:t,likes:e,views:r,comments:c,downloads:l})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img
              class="gallery-image"
              src="${s}"
              alt="${t}"
            />
            <ul class="gallery-info">
              <li class="gallery-info-item">Likes: <span class="descr-span">${e}</span></li>
              <li class="gallery-info-item">Views: <span class="descr-span">${r}</span></li>
              <li class="gallery-info-item">Comments: <span class="descr-span">${c}</span></li>
              <li class="gallery-info-item">Downloads: <span class="descr-span">${l}</span></li>
            </ul> 
          </a>
        </li>`).join("")}function h(){window.scrollBy({top:2*document.querySelector(".gallery-item").getBoundingClientRect().height,behavior:"smooth"})}const m=new g(".gallery-item a",{captionsData:"alt",captionDelay:250}),i={query:"",page:1,maxPage:0,per_page:15};o.form.addEventListener("submit",M);async function M(n){e(),n.preventDefault(),o.gallery.innerHTML="",i.page=1;const s=n.currentTarget;if(i.query=s.elements.query.value.trim(),!i.query){a("The search field can't be empty! Please, enter your request!"),t();return}function a(l){p.show({class:"error-svg",position:"topRight",icon:"error-svg",message:l,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}try{const{hits:l,totalHits:d}=await u(i);i.maxPage=Math.ceil(d/i.per_page),o.gallery.insertAdjacentHTML("beforeend",f(l)),m.refresh(),t(),l.length===0?(a("Sorry, there are no images matching your search query. Please, try again!"),t()):l.length>0&&l.length!==d?(c(),o.loadMoreBtn.addEventListener("click",y),t()):(r(),a("We are sorry, but you've reached the end of search results"))}catch{a("Sorry, there is a problem with connection with the server")}finally{t(),s.reset(),h()}function t(){setTimeout(()=>{o.loader.classList.add("is-hidden")},1e3)}function e(){o.loader.classList.remove("is-hidden")}function r(){o.loadMoreBtn.classList.add("is-hidden")}function c(){o.loadMoreBtn.classList.remove("is-hidden")}}async function y(){i.page+=1,s(),o.loadMoreBtn.disabled=!0;try{const{hits:t}=await u(i);o.gallery.insertAdjacentHTML("beforeend",f(t)),m.refresh()}catch{createMessage("Sorry, there is a problem with connection with the server")}finally{n(),o.loadMoreBtn.disabled=!1,i.page===i.maxPage&&(n(),a(),o.loadMoreBtn.removeEventListener("click",y),createMessage("We are sorry, but you've reached the end of search results")),h()}function n(){setTimeout(()=>{o.loader.classList.add("is-hidden")},1e3)}function s(){o.loader.classList.remove("is-hidden")}function a(){o.loadMoreBtn.classList.add("is-hidden")}}
//# sourceMappingURL=commonHelpers.js.map
